services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenger
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    ports:
      - "5432:5432"
    volumes:
      - ./Database/sql/schema-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data  # persist DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d challenger"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: challenger-api
    ports:
      - "8000:8000"
    env_file:
      - .env                               # inject variables
    volumes:
      - ./.env:/app/.env                  # <- mount so godotenv can read it
      - ./api:/app/api
      - ./common:/app/common
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    depends_on:
      postgres:
        condition: service_healthy

  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: challenger-chat
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./chat:/app/chat
      - ./common:/app/common
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
