version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challenger
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./Database/sql/schema-init:/docker-entrypoint-initdb.d

  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-init:/var/lib/neo4j/import

  api-gateway:
    build: ./Services/Api-Gateway
    ports:
      - "8080:8080"
    volumes:
      - ./Services/Api-Gateway:/app
    depends_on:
      - mysql
      - neo4j

  challenge-service:
    build: ./Services/Challenge-Service
    ports:
      - "8081:8081"
    volumes:
      - ./Services/Challenge-Service:/app
    depends_on:
      - mysql
      - neo4j

  chat-service:
    build: ./Services/Chat-Service
    ports:
      - "8082:8082"
    volumes:
      - ./Services/Chat-Service:/app
    depends_on:
      - mysql
      - neo4j

  user-service:
    build: ./Services/User-Service
    ports:
      - "8083:8083"
    volumes:
      - ./Services/User-Service:/app
    depends_on:
      - mysql
      - neo4j