version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenger
    ports:
      - "5432:5432"
    volumes:
      - ./Database/sql/schema-init:/docker-entrypoint-initdb.d

  api-gateway:
    build: ./Services/Api-Gateway
    ports:
      - "8080:8080"
    volumes:
      - ./Services/Api-Gateway:/app
    depends_on:
      - postgres

  challenge-service:
    build: ./Services/Challenge-Service
    ports:
      - "8081:8081"
    volumes:
      - ./Services/Challenge-Service:/app
    depends_on:
      - postgres

  chat-service:
    build: ./Services/Chat-Service
    ports:
      - "8082:8082"
    volumes:
      - ./Services/Chat-Service:/app
    depends_on:
      - postgres

  user-service:
    build: ./Services/User-Service
    ports:
      - "8083:8083"
    volumes:
      - ./Services/User-Service:/app
    depends_on:
      - postgres
