services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: challenger-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Database/sql/schema-init:/docker-entrypoint-initdb.d
    networks:
      - challenger-network

  app:
    image: challenger-app:latest
    container_name: challenger-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - challenger-network
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  postgres-data:

networks:
  challenger-network:
    driver: bridge
